[package]
name = "rg3d-ui"
version = "0.13.1"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "Extendable UI library"
keywords = ["ui", "game", "gui"]
repository = "https://github.com/mrDIMAS/rg3d"
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
readme = "README.md"

[dependencies]
rg3d-core = { path = "../rg3d-core", version = "0.17.1" }
lazy_static = "1.4.0"
copypasta = "0.7.1"
fontdue = "0.5.2"

[features]
enable_profiler = ["rg3d-core/enable_profiler"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sysinfo = "0.20.0"